baseURL = "gaygothvibes.online"
languageCode = "en-us"
title = "gay goth vibes dot online"
theme = "hugo-arcana"
copyright = "© satah"

defaultContentLanguage = "en"

capitalizeListTitles = false
pluralizeListTitles = false

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[taxonomies]
    tag = "tags"
    category = "category"

[params]
    description = "gay goth vibes dot online."
    images = ['images/selfie1.jpg']
    show_post_dates = true

    [[params.social]]
        title = "bluesky"
        icon = "fa-bluesky"
        url = "https://bsky.app/profile/posatahchips.gaygothvibes.online"
    [[params.social]]
        title = "instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/posatahchips/"


    [params.footer]
        [params.footer.contact_form]
            enabled = false
            header = "contact"
            action = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html']
