baseURL = "https://example.org/"
languageCode = "en-us"
title = "gay goth vibes dot online"
theme = "hugo-arcana"
copyright = "© Untitled. All rights reserved"

defaultContentLanguage = "en"

capitalizeListTitles = false
pluralizeListTitles = false

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[taxonomies]
    tag = "tags"
    category = "category"

[params]
    description = "gay goth vibes dot online."
    images = ['images/metaimage.jpg']
    show_post_dates = true

    [[params.social]]
        title = "Bluesky"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]

        [params.footer.contact_form]
            enabled = false
            header = "contact"
            action = ""
